using Infrastructure.Extensions;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Presentation.Extensions;
using Presentation.Infrastructure;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddInfrastructure(builder.Configuration);
builder.Services.AddSynapseAuthentication(builder.Configuration);

builder.Services.AddCors(options =>
{
    var origins = builder.Configuration
        .GetSection("Cors:AllowedOrigins")
        .Get<string[]>() ?? [];

    options.AddDefaultPolicy(policy => policy
        .WithOrigins(origins)
        .AllowAnyHeader()
        .AllowAnyMethod()
        .AllowCredentials());
});

builder.Services.AddControllers();
builder.Services.AddSynapseOpenApi();
builder.Services.AddProblemDetails();
builder.Services.AddExceptionHandler<AnalysisExceptionHandler>();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    // Document is generated by Microsoft.AspNetCore.OpenApi; Swashbuckle supplies only the UI,
    // so there is no second schema generator to keep in sync.
    app.MapOpenApi();

    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint(
            $"/openapi/{OpenApiExtensions.DocumentName}.json",
            "Synapse Analyzer API v1");

        options.RoutePrefix = "swagger";
        options.DocumentTitle = "Synapse Analyzer API";
        options.EnablePersistAuthorization();
        options.DisplayRequestDuration();
    });

    // Keeps a local stack usable without a separate migration step. A failure here is logged
    // rather than fatal, so the app still starts when Postgres is down and
    // /api/diagnostics/health can report which dependencies are missing.
    using var scope = app.Services.CreateScope();

    try
    {
        await scope.ServiceProvider.GetRequiredService<AppDbContext>().Database.MigrateAsync();
    }
    catch (Exception ex)
    {
        app.Services.GetRequiredService<ILogger<Program>>()
            .LogWarning(ex, "Database migration failed at startup; the API is running without a usable database.");
    }
}

app.UseExceptionHandler();

// Not redirecting in development: the SSE and presigned-upload flows are exercised over
// plain http locally, and a redirect would break the EventSource connection.
if (!app.Environment.IsDevelopment())
    app.UseHttpsRedirection();

app.UseCors();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
// Liveness only - for a dependency-aware view use /api/diagnostics/health.
app.MapGet("/health", () => Results.Ok(new { status = "healthy" }))
    .AllowAnonymous()
    .WithTags("Health")
    .WithSummary("Liveness probe. Reports nothing about dependencies.");

app.Run();
